# 日志设置
log:
  level:                   warn
  file:                    /tmp/log/mosdns.log

# 数据源设置
data_providers:
  - tag:                   geosite
    file:                  "/usr/share/v2ray/geosite.dat"
    auto_reload:           true

  - tag:                   geoip
    file:                  "/usr/share/v2ray/geoip.dat"
    auto_reload:           true

  # - tag:                   adlist
  #   file:                  "./rule/serverlist.txt"
  #   auto_reload:           true

  - tag:                   whitelist
    file:                  "./rule/whitelist.txt"
    auto_reload:           true

  - tag:                   hosts
    file:                  "./rule/hosts.txt"
    auto_reload:           true

  # - tag:                   blocklist
  #   file:                  "./rule/blocklist.txt"
  #   auto_reload:           true

  - tag:                   local_ptr
    file:                  "./rule/local-ptr.txt"
    auto_reload:           true
    
  # - tag:                   redirect
  #   file:                  "./rule/redirect.txt"
  #   auto_reload:           true

  - tag:                   gfwlist
    file:                  "/usr/share/passwall/rules/gfwlist.txt"
    auto_reload:           true

  - tag:                   proxy_host
    file:                  "/usr/share/passwall/rules/proxy_host.txt"
    auto_reload:           true

  - tag:                   proxy_ip
    file:                  "/usr/share/passwall/rules/proxy_ip.txt"
    auto_reload:           true

  - tag:                   cdncn
    file:                  "./rule/cdn_domain_list.txt"
    auto_reload:           true

  - tag:                   gfwip
    file:                  "./rule/gfw_ip_list.txt"
    auto_reload:           true

  - tag:                   domains_excluded
    file:                  "/usr/share/passwall/rules/domains_excluded.txt"
    auto_reload:           true

# 插件
plugins:
  - tag:                   "query_is_whitelist_domain"
    type:                  query_matcher
    args:
      domain:
        - "provider:whitelist"
        - "provider:domains_excluded"

  # - tag:                   "query_is_blocklist_domain"
  #   type:                  query_matcher
  #   args:
  #     domain:
  #       - "provider:blocklist"

  - tag:                   "query_is_local_domain"
    type:                  query_matcher
    args:
      domain:
        - "provider:geosite:cn"

  - tag:                   "query_is_proxy_domain"
    type:                  query_matcher
    args:
      domain:
        - "provider:gfwlist"
        - "provider:proxy_host"
        - "zh.ifixit.com"

  - tag:                   "query_is_cdn_domain"
    type:                  query_matcher
    args:
      domain:
        - "provider:cdncn"
        - "keyword:akamai"
        - "akadns.net"

  # - tag:                   "query_is_non_local_domain"
  #   type:                  query_matcher
  #   args:
  #     domain:
  #       - "provider:geosite:geolocation-!cn"

  - tag:                   "query_is_qtype65"
    type:                  query_matcher
    args:
      qtype:               [65]

  - tag:                   "query_is_local_ptr"
    type:                  query_matcher
    args:
      qtype:               [12]
      domain:
        - "provider:local_ptr"

  # - tag:                   "query_is_ad_domain"
  #   type:                  query_matcher
  #   args:
  #     domain:
  #       - "provider:adlist"

  - tag:                   "response_has_local_ip"
    type:                  response_matcher
    args:
      ip:
        - "provider:geoip:cn"

  - tag:                   "response_has_banned_ip"
    type:                  response_matcher
    args:
      ip:
        - "0.0.0.0"
        - "2001::/32"
        - "provider:proxy_ip"
        - "provider:gfwip"
        - "provider:geoip:telegram,facebook,netflix,twitter"

  - tag:                   "response_server_failed"
    type:                  response_matcher
    args:
      rcode: [2]

  - tag:                   "query_is_hosts_domain"
    type:                  hosts
    args:
      hosts:
        - "provider:hosts"

  # - tag:                   "query_is_redirect_domain"
  #   type:                  redirect
  #   args:
  #     rule:
  #       - "provider:redirect"

  - tag:                   "lazy_cache"
    type:                  cache
    args:
      size:                10240
      lazy_cache_ttl:      259200

  - tag:                   "forward_local"
    type:                  fast_forward
    args:
      upstream:
        - addr:            "218.2.2.2"
        - addr:            "218.2.135.1"

  - tag:                   "forward_alidns"
    type:                  fast_forward
    args:
      upstream:
        - addr:            "https://dns.alidns.com/dns-query"
          dial_addr:       "223.5.5.5"

  - tag:                   "forward_remote"
    type:                  fast_forward
    args:
      upstream:
        - addr:            "tls://1.1.1.1:853"
          enable_pipeline: true
        - addr:            "udpme://8.8.4.4"
          trusted: true

  - tag:                   "forward_backup"
    type:                  fast_forward
    args:
      upstream:
        - addr:            "https://doh.apad.pro/dns-query"
        - addr:            "https://a.passcloud.xyz/dns-query"
          trusted: true

  - tag: "ecs_cn"
    type: "ecs"
    args:
      auto: false # 仅适用于公网的服务器。本地运行不要启用这个功能。
      ipv4: "180.96.0.0"
      ipv6: "240e:3a0::"
      force_overwrite: true # 强制覆盖
      mask4: 11 # 用于 ipv4 地址的掩码 默认: 24。
      mask6: 28 # 用于 ipv6 地址的掩码 默认: 48。

  # - tag: ecs_tw
  #   type: ecs
  #   args:
  #     auto: false
  #     ipv4: "168.95.1.0"
  #     ipv6: "2001:b000:168::1"
  #     mask4: 22
  #     force_overwrite: true

  - tag: ttl_short
    type: ttl
    args:
      minimal_ttl: 60
      maximum_ttl: 3600

  - tag: ttl_long
    type: ttl
    args:
      minimal_ttl: 300
      maximum_ttl: 3600

  - tag:                   main_sequence
    type:                  sequence
    args:
      exec:
        - _misc_optm
        - query_is_hosts_domain
        - lazy_cache
        # - query_is_redirect_domain
        - if:              "query_is_whitelist_domain"
          exec:
            - forward_local
            - _return
        - if:              "query_is_qtype65 || query_is_local_ptr"
          exec:
            - _new_nxdomain_response
            - _return
        - if:              "query_is_local_domain"
          exec:
            - forward_local
            - _return
        - if:              "query_is_proxy_domain"
          exec:
            - _no_ecs
            - _prefer_ipv4
            - forward_remote
            - _return
        - if:              "query_is_cdn_domain"
          exec:
            - ecs_cn
            - _pad_query
            - forward_alidns
            - _return
        - primary:
            - ecs_cn
            - _pad_query
            - forward_alidns
            - ttl_short
            - if:          "(! response_has_local_ip) && [_response_valid_answer] || (response_has_banned_ip)"
              exec:
                - _drop_response
          secondary:
            - ecs_cn
            # - _prefer_ipv4
            - forward_backup
            - ttl_long
            - if: "response_server_failed"
              exec:
                - ecs_cn
                # - _prefer_ipv4
                - _pad_query
                - forward_remote
                - ttl_long
          fast_fallback:   200
          # always_standby:  true

# 服务器设置
servers:
  - exec:                  main_sequence
    listeners:
      - protocol:          udp
        addr:              :5335
      - protocol:          tcp
        addr:              :5335
